import { formatCurrency } from "@/lib/utils";

type ReportMetric = {
  label: string;
  value: number;
  format?: "currency" | "number";
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function metricValue(metric: ReportMetric) {
  return metric.format === "number"
    ? metric.value.toLocaleString()
    : formatCurrency(metric.value);
}

export async function renderDashboardReportPdf(input: {
  organizationName: string;
  title: string;
  metrics: ReportMetric[];
  rows: Array<Record<string, string | number | null>>;
}) {
  const headers = Object.keys(input.rows[0] ?? {});
  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      @page { margin: .55in; size: Letter; }
      * { box-sizing: border-box; }
      body { color: #111827; font-family: Arial, Helvetica, sans-serif; font-size: 12px; margin: 0; }
      header { border-bottom: 2px solid #111827; display: flex; justify-content: space-between; padding-bottom: 22px; }
      h1 { font-size: 28px; margin: 0; }
      .muted { color: #667085; }
      .metrics { display: grid; gap: 12px; grid-template-columns: repeat(4, 1fr); margin: 26px 0; }
      .metric { border: 1px solid #d0d5dd; border-radius: 12px; padding: 14px; }
      .metric span { color: #667085; display: block; font-size: 10px; letter-spacing: .12em; text-transform: uppercase; }
      .metric strong { display: block; font-size: 20px; margin-top: 8px; }
      table { border-collapse: collapse; width: 100%; }
      th { background: #f2f4f7; color: #475467; font-size: 10px; letter-spacing: .1em; padding: 10px; text-align: left; text-transform: uppercase; }
      td { border-bottom: 1px solid #eaecf0; padding: 10px; }
      footer { border-top: 1px solid #d0d5dd; bottom: 0; color: #667085; font-size: 10px; left: 0; padding-top: 10px; position: fixed; right: 0; }
    </style>
  </head>
  <body>
    <header>
      <div>
        <h1>${escapeHtml(input.title)}</h1>
        <div class="muted">${escapeHtml(input.organizationName)}</div>
      </div>
      <div class="muted">${new Date().toLocaleString()}</div>
    </header>
    <section class="metrics">
      ${input.metrics
        .map(
          (metric) => `<div class="metric"><span>${escapeHtml(metric.label)}</span><strong>${escapeHtml(metricValue(metric))}</strong></div>`,
        )
        .join("")}
    </section>
    <table>
      <thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead>
      <tbody>
        ${input.rows
          .map(
            (row) =>
              `<tr>${headers.map((header) => `<td>${escapeHtml(String(row[header] ?? ""))}</td>`).join("")}</tr>`,
          )
          .join("")}
      </tbody>
    </table>
    <footer>Generated by ClearKey Connect using tenant-scoped report data.</footer>
  </body>
</html>`;
  const { chromium } = await import("playwright");
  const browser = await chromium.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
    headless: true,
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });
    return await page.pdf({
      format: "Letter",
      printBackground: true,
      preferCSSPageSize: true,
    });
  } finally {
    await browser.close();
  }
}
